trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
 
  - task: Docker@2
    displayName: "Building and pushing Docker image with build arguments"
    inputs:
      command: buildAndPush
      repository: agilesam/pmis  
      dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
      containerRegistry: "SammyDockerHubSvcConnection"  
      tags: latest
      buildArguments: |
        NEXT_PUBLIC_API_BASE_URL=http://192.168.3.68:9090/
