trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Build and push Docker image to Docker Hub
  - task: Docker@2
    displayName: 'Building and pushing Docker image with build arguments'
    inputs:
      command: buildAndPush
      repository: agilesam/pmis # Replace with your Docker Hub repository
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      containerRegistry: 'SammyDockerHubSvcConnection' # Your Docker Hub service connection
      tags: latest
      buildArguments: |
        NEXT_PUBLIC_API_BASE_URL=http://192.168.3.68:9090/
