trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
      secureFile: "sammymathenge-web.pem"

  - script: |
      # Set correct permissions for the private key
      chmod 600 $(Agent.TempDirectory)/sammymathenge-web.pem

      # Start SSH agent
      eval $(ssh-agent -s)

      # Add SSH private key to the agent
      ssh-add $(Agent.TempDirectory)/sammymathenge-web.pem

      ssh -o StrictHostKeyChecking=no -p $(SSH_PORT) $(SSH_USERNAME)@$(SSH_HOST) << 'EOF'
        echo "SSH connection successful"

        # Navigate to the project directory
        cd pmis


        # Pull the latest code from the repository
        git reset --hard origin/main

        git pull

        # Install the latest dependencies
        npm install
        

        # Build the Docker image
        sudo docker build -t pmis .

        # Stop and remove the existing container if it exists
        sudo docker stop pmis-core || true
        sudo docker rm pmis-core || true

        # Run the new Docker container
        sudo docker run --name pmis-core -p 4000:3000 -d pmis

        sudo docker image prune -af

        sudo systemctl restart nginx


        echo "Deployment completed successfully"
      EOF
    displayName: "Deploying to server..."
