ReferenceNo * string;
OmbudsmanBranch * string;
ComplaintChannel * string;
PartyName * string;
PensionerNumber;
string;
PensionerIdentifierType;
integer($int32);
PensionerIdentificationNumber;
string;
PensionerFirstName;
string;
PensionerMiddleName;
string;
PensionerSurname;
string;
PensionerEmail;
string;
PensionerPhone;
string;
PensionerPersonalNo;
string;
ComplaintIssue * string;
RootCause * string;
PostalCodeId;
string($uuid);
PostalAddress;
string;
Status;
integer($int32);
Remarks;
string;
ReceivedAt;
string($date - time);
Attachments;
