export const allClients = [
  {
    firstName: "John",
    middleName: "Adam",
    lastName: "Doe",
    department: "Engineering",
    role: "Software Engineer",
    employeeNumber: "E12345",
    email: "john.doe@example.com",
  },
  {
    firstName: "Jane",
    middleName: "Marie",
    lastName: "Smith",
    department: "Human Resources",
    role: "HR Manager",
    employeeNumber: "E67890",
    email: "jane.smith@example.com",
  },
  {
    firstName: "Alice",
    middleName: "Elizabeth",
    lastName: "Johnson",
    department: "Marketing",
    role: "Marketing Specialist",
    employeeNumber: "E24680",
    email: "alice.johnson@example.com",
  },
  {
    firstName: "Bob",
    middleName: "Michael",
    lastName: "Brown",
    department: "Finance",
    role: "Financial Analyst",
    employeeNumber: "E13579",
    email: "bob.brown@example.com",
  },
  {
    firstName: "Carol",
    middleName: "Ann",
    lastName: "White",
    department: "Operations",
    role: "Operations Manager",
    employeeNumber: "E97531",
    email: "carol.white@example.com",
  },
  {
    firstName: "David",
    middleName: "William",
    lastName: "Green",
    department: "Sales",
    role: "Sales Representative",
    employeeNumber: "E35791",
    email: "david.green@example.com",
  },
  {
    firstName: "Eva",
    middleName: "Louise",
    lastName: "Black",
    department: "Customer Service",
    role: "Customer Service Representative",
    employeeNumber: "E46802",
    email: "eva.black@example.com",
  },
  {
    firstName: "Frank",
    middleName: "Thomas",
    lastName: "Brown",
    department: "IT",
    role: "Systems Administrator",
    employeeNumber: "E80246",
    email: "frank.brown@example.com",
  },
  {
    firstName: "Grace",
    middleName: "Sophia",
    lastName: "Wilson",
    department: "Research and Development",
    role: "Research Scientist",
    employeeNumber: "E91357",
    email: "grace.wilson@example.com",
  },
  {
    firstName: "Henry",
    middleName: "Joseph",
    lastName: "Taylor",
    department: "Product Management",
    role: "Product Manager",
    employeeNumber: "E02468",
    email: "henry.taylor@example.com",
  },
];
