"use client";
// import { useState } from "react";

// List of pension caps
const pensionCaps = [
  "CAP189",
  "CAP199",
  "CAP196",
  "APN/PK",
  "CAP190",
  "CAP195",
  "DSO/RK",
  "CAP195",
];

export const createSections = (
  filteredDesignations,
  countries,
  counties,
  constituencies,
  filteredPostalAddresses,
  filteredGrades,

  exitGroundOptions,
  pensionAwardOptions,
  activePensionCap,
  formData,
  mdaId
) => [
  {
    title: "Personal Information",
    // state: useState(true),
    fields: [
      {
        label: "Personal Number",
        name: "personal_number",
        type: "text",
        pensionCap: [
          "CAP189",

          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Service Number",
        name: "personal_number",
        type: "text",
        pensionCap: ["CAP199"],
      },
      {
        label: "First Name",
        name: "first_name",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Surname",
        name: "surname",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Other Name",
        name: "other_name",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Email Address",
        name: "email_address",
        type: "email",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Phone Number",
        name: "phone_number",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Date of Birth",
        name: "dob",
        type: "date",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Gender",
        name: "gender",
        type: "select",
        children: [
          { id: 0, name: "Male" },
          { id: 1, name: "Female" },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Tribe",
        name: "tribe",
        type: "text",

        pensionCap: ["CAP199"],
      },
      {
        label: "Ethnicity",
        name: "tribe",
        type: "text",

        pensionCap: ["CAP1996"],
      },
      {
        label: "Deaceased",
        name: "mortality_status",
        type: "select",
        children: [
          { id: 2, name: "No" },
          { id: 1, name: "Yes" },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Marital Status",
        name: "marital_status",
        type: "select",
        children: [
          { id: 0, name: "Single" },
          { id: 1, name: "Married" },
          { id: 2, name: "Divorced" },
          { id: 3, name: "Widowed" },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Type Of Identification",
        name: "identifier_type",
        type: "select",
        children: [
          { id: 0, name: "National ID" },
          { id: 1, name: "Passport No" },
        ],
        pensionCap: [
          "CAP189",

          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Type Of Identification",
        name: "identifier_type",
        type: "select",
        children: [
          { id: 0, name: "Civilian ID" },
          { id: 1, name: "Passport No" },
          { id: 2, name: "Military ID" },
        ],
        pensionCap: ["CAP199"],
      },
      {
        label: "National ID/Passport No.",
        name: "national_id",
        type: "text",
        pensionCap: [
          "CAP189",

          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Military ID",
        name: "national_id",
        type: "text",
        pensionCap: ["CAP199"],
      },
      {
        label: "KRA PIN",
        name: "kra_pin",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Designation",
        name: "designation_id",
        type: "autocomplete",
        children: filteredDesignations,
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Grade",
        name: "grade_id",
        type: "select",
        children: filteredGrades,
        pensionCap: [
          "CAP189",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Ranks",
        name: "grade_id",
        type: "select",
        children: filteredGrades,
        pensionCap: ["CAP199"],
      },
    ],
  },

  {
    title: "Contact Details",
    // state: useState(true),
    fields: [
      {
        label: "Country",
        name: "country_id",
        type: "select",
        children: countries.map((country) => ({
          id: country.id,
          name: country.country_name,
        })),
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "County",
        name: "county_id",
        type: "select",
        children: counties.map((county) => ({
          id: county.id,
          name: county.name,
        })),
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Constituency",
        name: "constituency_id",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Postal Address",
        name: "postal_address",
        type: "number",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Postal Code",
        name: "postal_code",
        type: "autocomplete",
        children: filteredPostalAddresses,
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "City/Town",
        name: "city_town",
        type: "text",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
    ],
  },

  {
    title: "Benefits",
    // state: useState(true),
    fields: [
      {
        label: "Exit Ground",
        name: "exit_ground_id",
        type: "select",
        children: exitGroundOptions,
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Pension Award",
        name: "pension_award_id",
        type: "select",
        children: pensionAwardOptions,

        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Has Commuted",
        name: "commutation_option_selection",
        type: "select",
        children: [
          { id: 0, name: "Yes", value: true },
          { id: 1, name: "No", value: false },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "commutation Option Selection Date",
        name: "commutation_option_selection_date",
        type: "date",

        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Monthly Salary in Ksh",
        name: "monthly_salary_in_ksh",
        type: "number",
        pensionCap: ["CAP199"],
      },
      {
        label: "Service Increment",
        name: "service_increments",
        type: "number",
        pensionCap: ["CAP199"],
      },
      {
        label: "Monthly Additional Pay",
        name: "monthly_aditional_pay",
        type: "number",
        pensionCap: ["CAP199"],
      },
      {
        label: "Women & Children Pension Scheme (WCPS)",
        name: "is_wcps",
        type: "select",
        children: [
          { id: 0, name: "Yes" },
          { id: 1, name: "No" },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",

          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Maintenance Case",
        name: "maintenance_case",
        type: "select",
        children: [
          { id: 0, name: "Yes" },
          { id: 1, name: "No" },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",

          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Person With Disability",
        name: "disability_status",
        type: "select",
        children: [
          { id: 0, name: "Yes" },
          { id: 1, name: "No" },
        ],
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      ...(formData.disability_status === 0
        ? [
            {
              label: "Tax Exempt Certificate Number",
              name: "tax_exempt_certificate_number",
              type: "text",
              pensionCap: [
                "CAP189",
                "CAP199",
                "CAP196",
                "APN/PK",
                "CAP190",
                "CAP195",
                "DSO/RK",
                "CAP195",
              ],
            },
            {
              label: "Tax Exempt Certificate Date",
              name: "tax_exempt_certificate_date",
              type: "date",
              pensionCap: [
                "CAP189",
                "CAP199",
                "CAP196",
                "APN/PK",
                "CAP190",
                "CAP195",
                "DSO/RK",
                "CAP195",
              ],
            },
          ]
        : []),
      {
        label: "Date of First Appointment",
        name: "date_of_first_appointment",
        type: "date",
        pensionCap: [
          "CAP189",
          "CAP199",

          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Date first elected",
        name: "date_of_first_appointment",
        type: "date",
        pensionCap: ["CAP196"],
      },
      {
        label: "Is Parliamenterian",
        name: "is_parliamentary",
        type: "date",
        pensionCap: ["CAP196"],
        hide: true,
      },
      {
        label: "Date of confirmation into pensionable Office",
        name: "date_of_confirmation",
        type: "date",
        pensionCap: [
          "CAP189",
          "CAP199",

          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Retirement Date",
        name: "retirement_date",
        type: "date",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Age on Discharge",
        name: "age_on_discharge",
        type: "number",
        pensionCap: ["CAP199"],
      },
      {
        label: "Date of Which Pension will Commence/Date Of Death ",
        name: "date_from_which_pension_will_commence",
        type: "date",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      ...(formData.notification_status
        ? [
            {
              label: "Authority of retirement Ref No.",
              name: "authority_for_retirement_reference",
              type: "text",
              pensionCap: [
                "CAP189",
                "CAP199",
                "CAP196",
                "APN/PK",
                "CAP190",
                "CAP195",
                "DSO/RK",
                "CAP195",
              ],
            },
            {
              label: "Authority for Retirement Dated",
              name: "authority_for_retirement_dated",
              type: "date",
              pensionCap: [
                "CAP189",
                "CAP199",
                "CAP196",
                "APN/PK",
                "CAP190",
                "CAP195",
                "DSO/RK",
                "CAP195",
              ],
            },
          ]
        : []),
      {
        label: "Last Pay Date",
        name: "last_pay_date",
        type: "date",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
      {
        label: "Last Basic Salary Amount",
        name: "last_basic_salary_amount",
        type: "number",
        pensionCap: [
          "CAP189",
          "CAP199",
          "CAP196",
          "APN/PK",
          "CAP190",
          "CAP195",
          "DSO/RK",
          "CAP195",
        ],
      },
    ],
  },
];
