name: Build and Push Docker Image

# Trigger the workflow on changes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using Docker Hub credentials from GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Replace with your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Replace with your Docker Hub password secret

      # Step 3: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: agilesam/pmis:latest
